services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: arctic_team
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: egor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - arctic-net

  backend:
    build: .
    container_name: backend-arctic
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/arctic_team
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - arctic-net

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - arctic-net

volumes:
  postgres_data:
  redis_data:

networks:
  arctic-net:
    driver: bridge
