spring:
  application:
    name: backend_for_arctic_team

  datasource:
    url: jdbc:postgresql://localhost:5432/arctic_team
    username: postgres
    password: egor

  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: JDPtGGTXFa92yrEMHEOnNNJvfkWern2d9CFudAdPgTk
  access-token-expiration: 900000
  refresh-token-expiration: 604800000