spring:
  application:
    name: backend_for_arctic_team

  datasource:
    url: jdbc:postgresql://localhost:5432/arctic_team
    username: postgres
    password: egor

  data:
    redis:
      host: redis-cache
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  redis:
    host: redis-cache
    port: 6379
jwt:
  secret: JDPtGGTXFa92yrEMHEOnNNJvfkWern2d9CFudAdPgTk
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

logging:
  level:
    com.arctic.backend_for_arctic_team: TRACE
    org.springframework.security: DEBUG

